[project]
name = "expense-tracker-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiosqlite>=0.21.0",
    "fastmcp>=2.13.0.2",
    "langchain-mcp-adapters>=0.1.13",
    "langchain-openai>=1.0.3",
]
